export const LOGIN = "LOGIN";
export const LOGIN_FULFILLED = "LOGIN_FULFILLED";
export const FETCH_TRASHCAN_STOCK = "FETCH_TRASHCAN_STOCK";
export const TRASHCAN_STOCK_FETCHED = "TRASHCAN_STOCK_FETCHED";
