# Geir's super duper, pooper scooper catalog service

##################################################################################################
# Catalog service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: catalog
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog
        version: v1
    spec:
      containers:
      - name: catalog
        image: gcr.io/apigee-trashcan-backends/catalog:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: anchorsecret
---
###########################################################################
# Ingress resource (gateway)
##########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /catalog
        backend:
          serviceName: catalog
          servicePort: 3000
---
###########################################################################
# EgressRules (allow access to our other services)
##########################################################################
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: httpbin-egress-rule
spec:
  destination:
    service: search-dot-apigee-trashcan-backends.appspot.com
  ports:
    - port: 80
      protocol: http
    - port: 443
      protocol: https
---
apiVersion: config.istio.io/v1alpha2
kind: EgressRule
metadata:
  name: httpbin-egress-rule
spec:
  destination:
    service: us-central1-trashcans-project.cloudfunctions.net
  ports:
    - port: 80
      protocol: http
    - port: 443
      protocol: https
---
